name: Continues Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
      - name: Copy build folder to server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build
          remote: buildTest
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
      - name: Copy packege json
        uses: garygrossgarten/github-action-scp@release
        with:
          local: package.json
          remote: buildTest/package.json
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
      - name: Run npm install on server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd buildTest/ && npm install
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
